### PR TITLE
Added the pop function to linked_lists.py

### PR DESCRIPTION
**Pull request by KanishkKhurana**
i have added the pop function to linked_lists.py.
incase there is any error please tell me.
happy hacking !

### CODE REVIEW

**Comment by marwanhawari** [comment]
closes #3
 
Looks good. Thanks for the contribution @KanishkKhurana!

**Comment by KanishkKhurana** [comment]
cheers !
hacktober accepted right ? @marwanhawari

**Comment by marwanhawari** [comment]
Yes, your PR was merged so it should be automatically counted.

**Comment by KanishkKhurana** [comment]
Awesome ! thank you so much !

**Comment by KanishkKhurana** [comment]
@marwanhawari  on my hacktoberfest page it says that this pull request will mature in 14 days .
if you have closed and merged this pr , then why isnt this counted ?
i am really sorry to keep bothering you but this is worrying me .

**Pull request merged**
